name: Self-host Docker Image
on:
  push:
    branches: [ main ]
  workflow_dispatch:

permissions:
  contents: read

env:
  DOCKER_IMAGE_VERSION: ${{ vars.SELF_HOST_DOCKER_IMAGE_VERSION }}  

jobs:
  build:
    runs-on: ubuntu-latest
    environment: self-host

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push (multi-arch)
        run: |
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg GITHUB_TOKEN=${{ secrets.SPARROW_GITHUB_TOKEN }} \
            -t ssparrowapi/sparrow-proxy:self-host-${DOCKER_IMAGE_VERSION} \
            -t ssparrowapi/sparrow-proxy:latest \
            --push .