name: Self-host Docker Image
on:
  workflow_dispatch:
    inputs:
      image_version:
        description: "Docker image version (e.g. 1.2.3)"
        required: true
        type: string

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    environment: self-host
    env:
      DOCKER_IMAGE_VERSION: ${{ inputs.image_version }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      - name: Build and push (multi-arch)
        run: |
          echo "Building version: ${DOCKER_IMAGE_VERSION}" 
          docker buildx build \
            --platform linux/amd64,linux/arm64 \
            --build-arg GITHUB_TOKEN=${{ secrets.SPARROW_GITHUB_TOKEN }} \
            -t sparrowapi/sparrow-proxy:${DOCKER_IMAGE_VERSION} \
            -t sparrowapi/sparrow-proxy:latest \
            --push .
